export interface MenuItem {
  path: string
  name: string
  label: string
  icon: string
  component: () => Promise<any>
  adminOnly?: boolean
  layoutMode?: 'standard' | 'wide' | 'fluid'
}

export const menuRoutes: MenuItem[] = [
  {
    path: '',
    name: 'dashboard',
    label: '概览',
    icon: 'i-carbon-chart-pie',
    component: () => import('@/views/Dashboard.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'overview',
    name: 'overview',
    label: '总览',
    icon: 'i-carbon-chart-multitype',
    component: () => import('@/views/AnalyticsEcharts.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'personal',
    name: 'personal',
    label: '农场预览',
    icon: 'i-carbon-sprout',
    component: () => import('@/views/Personal.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'friends',
    name: 'friends',
    label: '好友',
    icon: 'i-carbon-user-multiple',
    component: () => import('@/views/Friends.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'steal-settings',
    name: 'steal-settings',
    label: '偷菜设置',
    icon: 'i-carbon-sprout',
    component: () => import('@/views/StealSettings.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'workflow',
    name: 'workflow',
    label: '策略流程',
    icon: 'i-carbon-flow',
    component: () => import('@/views/Workflow.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'analytics',
    name: 'analytics',
    label: '作物图鉴',
    icon: 'i-carbon-catalog',
    component: () => import('@/views/Analytics.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'accounts',
    name: 'accounts',
    label: '账号',
    icon: 'i-carbon-user-settings',
    component: () => import('@/views/Accounts.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'settings',
    name: 'Settings',
    label: '设置',
    icon: 'i-carbon-settings',
    component: () => import('@/views/Settings.vue'),
    layoutMode: 'fluid',
  },
  {
    path: 'announcements',
    name: 'announcements',
    label: '公告管理',
    icon: 'i-carbon-notification',
    component: () => import('@/views/AnnouncementManager.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'system-logs',
    name: 'system-logs',
    label: '系统日志',
    icon: 'i-carbon-catalog',
    component: () => import('@/views/SystemLogs.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'admin-operation-logs',
    name: 'admin-operation-logs',
    label: '操作日志',
    icon: 'i-carbon-task',
    component: () => import('@/views/AdminOperationLogs.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'help-center-analytics',
    name: 'help-center-analytics',
    label: '帮助统计',
    icon: 'i-carbon-chart-custom',
    component: () => import('@/views/HelpCenterAnalytics.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'help-center-feedback',
    name: 'help-center-feedback',
    label: '帮助反馈',
    icon: 'i-carbon-chat',
    component: () => import('@/views/HelpCenterFeedback.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'users',
    name: 'users',
    label: '用户',
    icon: 'i-carbon-user-multiple',
    component: () => import('@/views/Users.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'account-ownership',
    name: 'account-ownership',
    label: '账号归属',
    icon: 'i-carbon-user-role',
    component: () => import('@/views/AccountOwnership.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
  {
    path: 'cards',
    name: 'cards',
    label: '卡密',
    icon: 'i-carbon-id-management',
    component: () => import('@/views/Cards.vue'),
    adminOnly: true,
    layoutMode: 'fluid',
  },
]
