CREATE TABLE IF NOT EXISTS `help_center_events` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `event_no` VARCHAR(40) NOT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `session_id` VARCHAR(64) NOT NULL DEFAULT '',
    `trace_id` VARCHAR(64) NOT NULL DEFAULT '',
    `user_id` BIGINT DEFAULT NULL,
    `username` VARCHAR(64) NOT NULL DEFAULT '',
    `user_role` VARCHAR(32) NOT NULL DEFAULT '',
    `article_id` VARCHAR(80) NOT NULL DEFAULT '',
    `article_title` VARCHAR(160) NOT NULL DEFAULT '',
    `article_category` VARCHAR(80) NOT NULL DEFAULT '',
    `section_id` VARCHAR(120) NOT NULL DEFAULT '',
    `section_title` VARCHAR(160) NOT NULL DEFAULT '',
    `source_page` VARCHAR(80) NOT NULL DEFAULT '',
    `source_route` VARCHAR(255) NOT NULL DEFAULT '',
    `source_context` VARCHAR(120) NOT NULL DEFAULT '',
    `target_route` VARCHAR(255) NOT NULL DEFAULT '',
    `audience_filter` VARCHAR(32) NOT NULL DEFAULT '',
    `quick_filter` VARCHAR(32) NOT NULL DEFAULT '',
    `result` VARCHAR(24) NOT NULL DEFAULT 'success',
    `error_code` VARCHAR(64) NOT NULL DEFAULT '',
    `latency_ms` INT NOT NULL DEFAULT 0,
    `meta_json` JSON DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_help_center_events_event_no` (`event_no`),
    KEY `idx_help_center_events_created_at` (`created_at`),
    KEY `idx_help_center_events_type_created` (`event_type`, `created_at`),
    KEY `idx_help_center_events_article_created` (`article_id`, `created_at`),
    KEY `idx_help_center_events_trace_created` (`trace_id`, `created_at`),
    KEY `idx_help_center_events_source_created` (`source_page`, `created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '帮助中心原始埋点事件表';
