CREATE TABLE IF NOT EXISTS `help_center_feedback` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `feedback_no` VARCHAR(40) NOT NULL,
    `article_id` VARCHAR(80) NOT NULL DEFAULT '',
    `article_title` VARCHAR(160) NOT NULL DEFAULT '',
    `section_id` VARCHAR(120) NOT NULL DEFAULT '',
    `section_title` VARCHAR(160) NOT NULL DEFAULT '',
    `feedback_type` VARCHAR(32) NOT NULL DEFAULT 'other',
    `priority` VARCHAR(16) NOT NULL DEFAULT 'medium',
    `status` VARCHAR(24) NOT NULL DEFAULT 'open',
    `username` VARCHAR(64) NOT NULL DEFAULT '',
    `user_role` VARCHAR(32) NOT NULL DEFAULT '',
    `source_page` VARCHAR(80) NOT NULL DEFAULT '',
    `source_route` VARCHAR(255) NOT NULL DEFAULT '',
    `source_context` VARCHAR(120) NOT NULL DEFAULT '',
    `audience_filter` VARCHAR(32) NOT NULL DEFAULT '',
    `quick_filter` VARCHAR(32) NOT NULL DEFAULT '',
    `message` TEXT NOT NULL,
    `expected_behavior` TEXT NULL,
    `actual_behavior` TEXT NULL,
    `attachment_meta` JSON DEFAULT NULL,
    `assigned_to` VARCHAR(64) NOT NULL DEFAULT '',
    `owner_team` VARCHAR(64) NOT NULL DEFAULT '',
    `linked_bug_report_no` VARCHAR(40) NOT NULL DEFAULT '',
    `last_follow_up_at` TIMESTAMP NULL DEFAULT NULL,
    `resolved_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_help_center_feedback_no` (`feedback_no`),
    KEY `idx_help_center_feedback_status_created` (`status`, `created_at`),
    KEY `idx_help_center_feedback_article_created` (`article_id`, `created_at`),
    KEY `idx_help_center_feedback_assigned_status` (`assigned_to`, `status`),
    KEY `idx_help_center_feedback_type_created` (`feedback_type`, `created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '帮助中心文档治理反馈表';
